### ISSUE TITLE
Environment not properly handled by pagelet includes

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#22]
Includes defined by a pagelet definition always link to the production url. URLs for includes defined by a template definition reflect the current environment.

Sample output code (comments added):

``` HTML
<!-- Includes defined by template -->
<script jquery="1.2.8" use="renderer" src="http://api.swissunihockey:8080/weblounge-sites/webservices/js/supersubs-0.2b.js" type="text/javascript"></script>
<script jquery="1.5.1" use="renderer" src="http://api.swissunihockey:8080/weblounge-sites/webservices/js/hoverIntent-r6.js" type="text/javascript"></script>
<script jquery="1.2.8" use="renderer" src="http://api.swissunihockey:8080/weblounge-sites/webservices/js/menue.js" type="text/javascript"></script>
<!-- Includes defined by pagelets -->
<link use="renderer" href="http://api.swissunihockey.ch/weblounge-sites/webservices/modules/text/css/title.css" type="text/css" rel="stylesheet"></link>
<script use="renderer" src="http://api.swissunihockey.ch/weblounge-sites/webservices/modules/text/js/prettify.js" type="text/javascript"></script>
<script use="renderer" src="http://api.swissunihockey.ch/weblounge-sites/webservices/modules/text/js/code.js" type="text/javascript"></script>
```

**Comment by myniva** [comment]
The attached patch seems to fix the problem. Please validate.

```
diff --git a/modules/weblounge-common/src/main/java/ch/entwine/weblounge/common/impl/content/page/PageletRendererImpl.java b/modules/weblounge-common/src/main/java/ch/entwine/weblounge/common/impl/content/page/PageletRendererImpl.java
index 4ad176a..85d2303 100644
--- a/modules/weblounge-common/src/main/java/ch/entwine/weblounge/common/impl/content/page/PageletRendererImpl.java
+++ b/modules/weblounge-common/src/main/java/ch/entwine/weblounge/common/impl/content/page/PageletRendererImpl.java
@@ -114,7 +114,6 @@
       htmlHead.setSite(site);
       htmlHead.setModule(module);
     }
-    processURLTemplates(environment);
   }

   /**
```

**Comment by ghost** [comment]
Fixed. Added an integration test to ensure the functionality. Also, took the opportunity to run the integration tests against the site's url instead of a hard coded 127.0.0.1.

**Comment by myniva** [comment]
The bug does still exists in develop branch (5ecc20c4296ae0f43b39e5f4df52114583710c21).

**Comment by myniva** [comment]
There's a new branch 't/22' where this bug is fixed. Please merge into develop and delete this branch after the solution is accepted.

**Comment by ghost** [comment]
Did some initial work to keep your change consistent with my recent changes trying to overcome this issue. Also added an integration test that will make sure the includes are properly reflecting the environment.
