### ISSUE TITLE
Weblounge intermittently hangs during startup

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#290]
The logs always look the same. After "Starting rest publishing service", there is no more output:

2013-08-08 03:43:12  INFO (WebloungeKernel:53) Starting common weblounge services
2013-08-08 03:43:12  INFO (WebloungeKernel:57) Starting job scheduler
2013-08-08 03:43:12  INFO (DispatcherServiceImpl:100) Activating weblounge dispatcher
2013-08-08 03:43:12  INFO (DispatcherServiceImpl:111) Instance name is 'Standalone'
2013-08-08 03:43:12  INFO (SharedHttpContextImpl:113) Enabling requests to protected resources
2013-08-08 03:43:12  INFO (SharedHttpContextImpl:61) Publishing shared http context
2013-08-08 03:43:12  INFO (WebloungeSharedResources:179) Serving shared resources at /weblounge-shared
2013-08-08 03:43:12  INFO (EndpointPublishingService:124) Starting rest publishing service

**Comment by ghost** [comment]
After attaching the debugger, it turns out that Weblounge is hanging in the following stack:

waiting for: ServiceRegistry  (id=65)
Object.wait(long) line: not available [native method]
ServiceRegistry(Object).wait() line: 502
ServiceRegistry.getService(Bundle, ServiceReference<S>) line: 281
Felix.getService(Bundle, ServiceReference<S>) line: 3568
BundleContextImpl.getService(ServiceReference<S>) line: 468
EndpointPublishingService$JSR311AnnotatedServiceListener.serviceChanged(ServiceEvent) line: 332
EndpointPublishingService.activate(ComponentContext) line: 158
...

**Comment by ghost** [comment]
Fixed by ignoring bundle in "starting" stage during inital scan.

**Comment by myniva** [comment]
Error still occurs with current develop code-base. Are there any changes in the code associated with this issue elsewhere?

Maybe updating the Felix SCR component would help as well, see https://issues.apache.org/jira/browse/FELIX-2450

**Comment by myniva** [comment]
Updating Felix SCR to version 1.8.2 seems to help. Instead of blocking the log now occasionally outputs some error messages:

```
2014-08-20 06:48:27  INFO (WebloungeSharedResources:179) - Serving shared resources at /weblounge-shared
2014-08-20 06:48:27  INFO (EndpointPublishingService:124) - Starting rest publishing service
2014-08-20 06:48:32 ERROR (?:?) - [Weblounge Endpoint Runtime Information(33)] Cannot create component instance due to failure to bind reference endpointpublisher
2014-08-20 06:48:32 ERROR (?:?) - [Weblounge Endpoint Runtime Information(33)] Failed creating the component instance; see log for reason
2014-08-20 06:48:32 ERROR (?:?) - [Weblounge Endpoint Runtime Information(33)] Cannot create component instance due to failure to bind reference endpointpublisher
2014-08-20 06:48:32 ERROR (?:?) - [Weblounge Endpoint Runtime Information(33)] Failed creating the component instance; see log for reason
2014-08-20 06:48:34  INFO (SpringSecurityConfigurationService:221) - Enabling spring security
2014-08-20 06:48:34  INFO (SpringSecurityConfigurationService:234) - Securing the Felix management console
```

**Comment by myniva** [comment]
There's an other error message which occurs from time to time:

```
2014-08-20 10:07:22 ERROR (?:?) - [Weblounge Endpoint Runtime Information(33)] Circular reference detected, getService returning null
```

But the system is still starting without any problems.

**Comment by myniva** [comment]
Unfortunately the problem does not seem to be completely gone with the update of Felix SCR to 1.8.2. I can still observe it from time to time.
